import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import ThemeToggle from "@/components/ThemeToggle";
import farmLogo from "@/components/assets/farm-logo.svg";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <nav className="flex flex-row items-center gap-6 p-6 bg-base-100 shadow-md">
          <div className="flex flex-row items-center justify-start ml-12 mr-auto">
            <Link href={"/"} className="flex flex-row gap-2 items-center">
              <Image width={32} height={32} src={farmLogo} alt="Farm Logo"/>
              <span className="text-lg font-bold text-primary">FarmDB</span>
            </Link>
          </div>
          <div className="flex flex-row items-center gap-6 mr-12">
            <Link href={"/"} className="text-neutral hover:text-primary transition-colors">Home</Link>
            <Link href={"/about"} className="text-neutral hover:text-primary transition-colors">About</Link>
            <Link href={"/cropdb"} className="text-neutral hover:text-primary transition-colors">Crop Database</Link>
            <Link href={"/ai"} className="text-neutral hover:text-primary transition-colors">AI analysis</Link>
            <Link href={"/account"} className="text-neutral hover:text-primary transition-colors">Account</Link>
            <Link href={"/upgrade"} className="btn btn-secondary btn-sm">Upgrade</Link>
            <ThemeToggle />
          </div>
        </nav>
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
